version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: redis_repo_container

  db:
    image: postgres
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=repo_automator_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    container_name: postgres_repo_container

  app:
    build: .
    volumes:
    - .:/repo_automator
    ports:
    - 8000:8000
    image: app:repo_automator
    container_name: django_repo_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  celery:
    restart: on-failure
    build:
      context: .
    command: celery --app repo worker -l DEBUG
    volumes:
    - .:/repo_automator
    container_name: celery_repo_container
    depends_on:
      - db
      - redis
      - app
