version: '3'
services:
  repo_api:
    container_name: repo_api
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/repo_api
    ports:
      - "5432:5432"
    volumes:
      - repo_api:/data/repo_api
    restart: always

  
  pgadmin:
    container_name: repo_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
    ports:
      - "6050:80"


volumes:
  repo_api: