version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis_repo_container
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/repo_automator/staticfiles
    ports:
      - 80:80
    depends_on:
      - app
  
  app:
    build: .
    volumes:
    - .:/repo_automator
    - static_volume:/repo_automator/staticfiles
    container_name: django_repo_container
    command: gunicorn repo.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    
  db:
    container_name: db_repo_automator
    image: postgres
    env_file:
      - .env
    volumes:
      - repo_db:/data/repo_db
    restart: always

  

  celery:
    restart: on-failure
    build:
      context: .
    command: celery --app repo worker -l DEBUG
    
    volumes:
    - .:/repo_automator
    container_name: celery_repo_container
    depends_on:
      - db
      - redis
      - app


volumes:
  repo_db:
  static_volume:
