version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis_repo_container
    
  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - repo_db:/data/repo_db
    restart: always

  app:
    build: .
    volumes:
    - .:/repo_automator
    ports:
    - 8005:8000
    image: app:repo_automator
    container_name: django_repo_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  celery:
    restart: on-failure
    build:
      context: .
    command: celery --app repo worker -l DEBUG
    
    volumes:
    - .:/repo_automator
    container_name: celery_repo_container
    depends_on:
      - db
      - redis
      - app

volumes:
  repo_db:
