# Generated by Django 4.1.4 on 2023-01-12 20:40

import automate.encryptor.crypt
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the project", max_length=200, unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "primary_repo_owner",
                    models.CharField(help_text="Primary repo owner", max_length=100),
                ),
                (
                    "primary_repo_name",
                    models.CharField(help_text="Primary repo name", max_length=100),
                ),
                (
                    "primary_repo_token",
                    automate.encryptor.crypt.EncryptedCharField(
                        help_text="Access Token for primary repo", max_length=100
                    ),
                ),
                (
                    "primary_repo_type",
                    models.CharField(
                        choices=[("github", "Github"), ("bitbucket", "Bitbucket")],
                        default="github",
                        max_length=50,
                    ),
                ),
                (
                    "primary_repo_project_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary Repo project name; If repo is bitbucket",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "secondary_repo_owner",
                    models.CharField(help_text="Secondary repo owner", max_length=100),
                ),
                (
                    "secondary_repo_name",
                    models.CharField(help_text="Secondary repo name", max_length=100),
                ),
                (
                    "secondary_repo_token",
                    automate.encryptor.crypt.EncryptedCharField(
                        help_text="Access Token for secondary repo", max_length=100
                    ),
                ),
                (
                    "secondary_repo_type",
                    models.CharField(
                        choices=[("github", "Github"), ("bitbucket", "Bitbucket")],
                        default="github",
                        max_length=50,
                    ),
                ),
                (
                    "secondary_repo_project_name",
                    models.CharField(
                        blank=True,
                        help_text="Secondary Repo project name; If repo is bitbucket",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pr_id", models.IntegerField()),
                ("action", models.CharField(max_length=30, null=True)),
                ("body", models.TextField()),
                ("url", models.URLField(help_text="url link for the new PR")),
                (
                    "primary_url",
                    models.URLField(help_text="url link for the initial PR"),
                ),
                ("author", models.CharField(max_length=200)),
                ("comments", models.IntegerField(default=0)),
                ("merged_at", models.DateTimeField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automate.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
