# Generated by Django 4.1.4 on 2022-12-21 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automate.basemodel",
                    ),
                ),
                ("pr_id", models.IntegerField()),
                ("action", models.CharField(max_length=30, null=True)),
                ("body", models.TextField()),
                ("url", models.URLField()),
                ("author", models.CharField(max_length=200)),
                ("merged_at", models.DateTimeField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
            ],
            bases=("automate.basemodel",),
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automate.basemodel",
                    ),
                ),
                (
                    "primary_repo",
                    models.CharField(
                        help_text="Name of original repository", max_length=100
                    ),
                ),
                (
                    "primary_repo_url",
                    models.CharField(
                        help_text="The url repository to be copied from", max_length=500
                    ),
                ),
                (
                    "primary_repo_type",
                    models.CharField(
                        choices=[("github", "Github"), ("gitbucket", "Gitbucket")],
                        default="github",
                        max_length=50,
                    ),
                ),
                (
                    "secondary_repo",
                    models.CharField(
                        help_text="Name of repository that new changes would be pushed to",
                        max_length=100,
                    ),
                ),
                (
                    "secondary_repo_url",
                    models.CharField(
                        help_text="The url repository that new changes would be pushed to",
                        max_length=500,
                    ),
                ),
                (
                    "secondary_repo_type",
                    models.CharField(
                        choices=[("github", "Github"), ("gitbucket", "Gitbucket")],
                        default="github",
                        max_length=50,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("automate.basemodel",),
        ),
    ]
