# Generated by Django 3.2.16 on 2023-01-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="base",
            field=models.CharField(
                default="main",
                help_text="The branch you want to target with PR changes. i.e., main",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="primary_token",
            field=models.TextField(
                default="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",
                help_text="Primary Access token to make PR changes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="primary_username",
            field=models.CharField(
                default="kramstyles",
                help_text="The git username for the primary repository",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="secondary_token",
            field=models.TextField(
                default="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",
                help_text="Secondary Access token to make PR changes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="secondary_username",
            field=models.CharField(
                default="kramstyles",
                help_text="The git username for the secondary repository",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pr_id", models.IntegerField()),
                ("action", models.CharField(max_length=30, null=True)),
                ("body", models.TextField()),
                ("url", models.URLField()),
                ("author", models.CharField(max_length=200)),
                ("merged_at", models.DateTimeField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automate.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
