# Generated by Django 4.1.4 on 2022-12-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="slug",
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
