# Generated by Django 4.1.4 on 2022-12-22 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("automate", "0002_repository_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="automate.basemodel",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of task or project i.e copy from parent to child",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "primary_repo",
                    models.CharField(
                        help_text="Name of original repository", max_length=100
                    ),
                ),
                (
                    "primary_repo_url",
                    models.CharField(
                        help_text="The url repository to be copied from", max_length=500
                    ),
                ),
                (
                    "primary_repo_type",
                    models.CharField(
                        choices=[("github", "Github"), ("gitbucket", "Gitbucket")],
                        default="github",
                        max_length=50,
                    ),
                ),
                (
                    "secondary_repo",
                    models.CharField(
                        help_text="Name of repository that new changes would be pushed to",
                        max_length=100,
                    ),
                ),
                (
                    "secondary_repo_url",
                    models.CharField(
                        help_text="The url repository that new changes would be pushed to",
                        max_length=500,
                    ),
                ),
                (
                    "secondary_repo_type",
                    models.CharField(
                        choices=[("github", "Github"), ("gitbucket", "Gitbucket")],
                        default="github",
                        max_length=50,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("automate.basemodel",),
        ),
        migrations.DeleteModel(
            name="Repository",
        ),
    ]
