# Generated by Django 4.1.4 on 2022-12-23 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("automate", "0002_repository_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of task or project i.e copy from parent to child",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "primary_repo",
                    models.CharField(
                        help_text="Name of original repository", max_length=100
                    ),
                ),
                (
                    "primary_repo_url",
                    models.CharField(
                        help_text="The url repository to be copied from", max_length=500
                    ),
                ),
                (
                    "primary_repo_type",
                    models.CharField(
                        choices=[("github", "Github"), ("gitbucket", "Gitbucket")],
                        default="github",
                        max_length=50,
                    ),
                ),
                (
                    "secondary_repo",
                    models.CharField(
                        help_text="Name of repository that new changes would be pushed to",
                        max_length=100,
                    ),
                ),
                (
                    "secondary_repo_url",
                    models.CharField(
                        help_text="The url repository that new changes would be pushed to",
                        max_length=500,
                    ),
                ),
                (
                    "secondary_repo_type",
                    models.CharField(
                        choices=[("github", "Github"), ("gitbucket", "Gitbucket")],
                        default="github",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="history",
            name="basemodel_ptr",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="basemodel_ptr",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="owner",
        ),
        migrations.DeleteModel(
            name="BaseModel",
        ),
        migrations.DeleteModel(
            name="History",
        ),
        migrations.DeleteModel(
            name="Repository",
        ),
    ]
