# Generated by Django 3.2.16 on 2023-01-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0002_auto_20230104_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
