# Generated by Django 3.2.16 on 2023-01-14 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0003_projectactivities_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectactivities",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
    ]
