# Generated by Django 3.2.16 on 2023-01-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0004_auto_20230106_0656"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="primary_token",
        ),
        migrations.RemoveField(
            model_name="project",
            name="primary_username",
        ),
        migrations.RemoveField(
            model_name="project",
            name="secondary_token",
        ),
        migrations.RemoveField(
            model_name="project",
            name="secondary_username",
        ),
        migrations.AddField(
            model_name="project",
            name="primary_repo_url",
            field=models.CharField(
                default="https://github.com/kramstyles/pacesetter-utils.git",
                help_text="The url repository to be copied from",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="secondary_repo_url",
            field=models.CharField(
                default="https://github.com/kramstyles/pacesetter-utils.git",
                help_text="The url repository to be copied to",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="primary_repo_token",
            field=models.TextField(help_text="Access Token for primary repo"),
        ),
        migrations.AlterField(
            model_name="project",
            name="primary_repo_type",
            field=models.CharField(
                choices=[("github", "Github"), ("bitbucket", "Bitbucket")],
                default="github",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="secondary_repo_token",
            field=models.TextField(help_text="Access Token for secondary repo"),
        ),
        migrations.AlterField(
            model_name="project",
            name="secondary_repo_type",
            field=models.CharField(
                choices=[("github", "Github"), ("bitbucket", "Bitbucket")],
                default="github",
                max_length=50,
            ),
        ),
    ]
