# Generated by Django 4.1.4 on 2023-01-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0004_alter_projectactivities_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
