# Generated by Django 3.2.16 on 2023-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automate", "0006_auto_20230122_0113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="primary_client_id",
            field=models.TextField(
                null=True, verbose_name="Primary Bitbucket ClientID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="primary_client_secret",
            field=models.TextField(
                null=True, verbose_name="Primary Bitbucket Client Secret"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="primary_refresh_token",
            field=models.TextField(
                null=True, verbose_name="Primary Bitbucket Refresh Token"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="secondary_client_id",
            field=models.TextField(
                null=True, verbose_name="Secondary Bitbucket ClientID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="secondary_client_secret",
            field=models.TextField(
                null=True, verbose_name="Secondary Bitbucket Client Secret"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="secondary_refresh_token",
            field=models.TextField(
                null=True, verbose_name="Secondary Bitbucket Refresh Token"
            ),
        ),
    ]
