# Generated by Django 4.1.4 on 2023-01-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
