name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  SECRET_KEY: envSecretKey
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: localhost

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run flake8 tests
      run: |
        flake8 .
    - name: Run docformatter tests
      run: |
        docformatter --check --diff .
    - name: Run isort tests
      run: |
        isort .
    - name: Run black tests
      run: |
        black --check .
    - name: Run pylint tests
      run: |
        pylint .
    - name: Run black tests
      run: |
        black --check .
